// <auto-generated />
using System;
using LivrariaApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LivrariaApi.Migrations
{
    [DbContext(typeof(LivrariaContext))]
    [Migration("20260601033757_AddTabelaPedidos")]
    partial class AddTabelaPedidos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("LivrariaCore.Models.Livro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PedidoId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Preco")
                        .HasColumnType("REAL");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoLivro")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("Livros");

                    b.HasDiscriminator<string>("TipoLivro").HasValue("Livro");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("LivrariaCore.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusPedido")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TelefoneCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("LivrariaCore.Models.LivroDigital", b =>
                {
                    b.HasBaseType("LivrariaCore.Models.Livro");

                    b.Property<string>("Formato")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Digital");
                });

            modelBuilder.Entity("LivrariaCore.Models.LivroFisico", b =>
                {
                    b.HasBaseType("LivrariaCore.Models.Livro");

                    b.Property<string>("TipoCapa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Fisico");
                });

            modelBuilder.Entity("LivrariaCore.Models.Livro", b =>
                {
                    b.HasOne("LivrariaCore.Models.Pedido", null)
                        .WithMany("Livros")
                        .HasForeignKey("PedidoId");
                });

            modelBuilder.Entity("LivrariaCore.Models.Pedido", b =>
                {
                    b.Navigation("Livros");
                });
#pragma warning restore 612, 618
        }
    }
}
